[package]
name = "rtsp_track"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
vrt          = { workspace = true }
vrt-rfdetr   = { workspace = true }
vrt-track    = { workspace = true }
vrt-reid     = { workspace = true }
sensor-rtsp  = { workspace = true }
kornia-image = { workspace = true }
vrt-hub      = { workspace = true, features = ["hub", "builder"] }
env_logger   = { workspace = true }
