[package]
name = "rtsp_rfdetr"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
vrt          = { workspace = true }
vrt-rfdetr   = { workspace = true }
sensor-rtsp  = { workspace = true }
vrt-hub      = { workspace = true, features = ["hub", "builder"] }
kornia-image = { workspace = true }
kornia-io    = { workspace = true }
env_logger   = { workspace = true }
